config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/dashboard', to: 'users#dashboard'

  root to: 'pages#home'

  resources :cuties do
    resources :rentals, only: [ :index, :show, :new, :create, :edit, :update ] do
      resources :reviews, only: [ :new, :create ]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cutie.rb
class Cutie < ApplicationRecord
  belongs_to :user
  has_many :rentals
  validates :ad_title, :name, :animal_type, :age, :gender, :hourly_price, presence: true
  validates :ad_title, uniqueness: true
  validates :age, numericality: { only_integer: true }
  mount_uploader :photo, PhotoUploader
  include PgSearch::Model
  pg_search_scope :search_by_name_and_animal_type,
   against: [ :name, :animal_type ],
   using: {
    tsearch: { prefix: true }
  }
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :cutie
  belongs_to :user
  validates :start_date, :end_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :rental

  validates :rating, :comment, presence: true
  validates :rating, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :owned_cuties, class_name: "Cutie"
  has_many :rentals
  has_many :rented_cuties, through: :rentals, source: :cutie
  has_many :reviews
  validates :age, numericality: { greater_than_or_equal_to: 18 }
  validates :age, numericality: { only_integer: true }
  mount_uploader :photo, PhotoUploader

  #Display the cuti-rental-requests to an owner
  def owner_rent_out
    cuties = []
    Rental.all.each do |r|
      temp_arr = []
      if r.cutie.user == self
        temp_arr[0] = r.cutie
        temp_arr[1] = r
        cuties << temp_arr
      end
    end
    return cuties
  end

  [Cutie.first, Rental.first]
  #Display the cuties which a user requested to rent
  def renter_rent
    cuties = []
    Rental.all.each do |r|
      temp_arr = []
      if r.user == self
        temp_arr[0] = r.cutie
        temp_arr[1] = r
        cuties << temp_arr
      end
    end
    return cuties
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index]
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :authenticate_user!, only: :home

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :phone_number, :street, :postcode, :city, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:age, :phone_number, :street, :postcode, :city, :photo])
  end
end

app/controllers/cuties_controller.rb
class CutiesController < ApplicationController
  before_action :find_cutie, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query] && params[:query] != ""
      @cuties = Cutie.search_by_name_and_animal_type("#{params[:query]}")
    else
      @cuties = Cutie.all
    end
  end

  def show
  end

  def new
    # @user is needed for our form
    @user = current_user
    @cutie = Cutie.new
  end

  def create
    @cutie = Cutie.new(cutie_params)
    @user = current_user
    @cutie.user = @user
    save_cutie(@cutie)
  end

  def edit
  end

  def update
    @cutie.update(cutie_params)
    redirect_to cuty_path(@cutie)
  end

  def destroy
    @cutie.destroy
    redirect_to cuties_path
  end

  private

  # To allow user input from Cutie Create Form to be whitelisted
  def cutie_params
    params.require(:cutie).permit(:ad_title, :name, :animal_type, :age, :gender, :hourly_price, :description, :photo)
  end

  # To save Cuties to our database
  def save_cutie(cutie)
    if cutie.save
      redirect_to cuty_path(cutie)
    else
      render :new
    end
  end

  def find_cutie
    @cutie = Cutie.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @cuties = Cutie.all
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def new
    @rental = Rental.new
    @cutie = Cutie.find(params[:cuty_id])
  end

  def create
    @rental = Rental.new(rental_params)
    @user = current_user
    @cutie = Cutie.find(params[:cuty_id])
    @rental.cutie = @cutie
    @rental.user = @user
    if @rental.save
      redirect_to dashboard_path(@user), notice: 'The request was send successfully.'
    else
      render :new, notice: 'Check your dates'
    end
  end

  def edit
    @cutie = Cutie.find(params[:cuty_id])
    @rental = Rental.find(params[:id])
  end

  def update
    @rental = Rental.find(params[:id])
    @rental.update(params.require(:rental).permit(:status))
    redirect_to dashboard_path, notice: 'The request was send successfully.'
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @rental = Rental.find(params[:rental_id])
    @cutie = @rental.cutie
    @user = @rental.user
  end

  def create
    @review = Review.new(review_params)
    @rental = Rental.find(params[:rental_id])
    @user = @rental.user
    @user_now = current_user
    @review.rental = @rental
    @review.user = @user
    if @review.save
      redirect_to dashboard_path(@user_now), notice: 'The review was send successfully.'
    else
      render :new, notice: 'Check your Review'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # This creates the dashboard for the user to see their bookings
  # The dashboard.html.erb still has to be styled
  def dashboard
    @user = current_user
    @cuties = Cutie.where(user: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuties/create.html.erb
<h1>Cuties#create</h1>
<p>Find me in app/views/cuties/create.html.erb</p>

app/views/cuties/destroy.html.erb
<h1>Cuties#destroy</h1>
<p>Find me in app/views/cuties/destroy.html.erb</p>

app/views/cuties/edit.html.erb
<h1>Update your Cutie</h1>

<%= simple_form_for [@cutie] do |c| %>
<%= c.input :ad_title %>
<%= c.input :name %>
<%= c.input :animal_type %>
<%= c.input :age %>
<%= c.input :gender %>
<%= c.input :hourly_price %>
<%= c.input :description %>
<%= c.input :photo %>
<%= c.input :photo_cache, as: :hidden %>
<%= c.submit "Update your cutie" %>
<% end %>

app/views/cuties/index.html.erb
<div class="container">
  <div class="row">
    <h1 class= 'mx-auto my-3'>See all Cuties</h1>
  </div>


  <%= simple_form_for cuties_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <%= text_field_tag :query,
      params[:query],
      class: "form-control string required", id: "search_query",
        placeholder: "Find a Cutie"
        %>
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i> Search
        </button>
    </div>
  <% end %>


    <div class="row my-3">
      <% @cuties.each do |cutie| %>
      <div class="col-xs-12 col-sm-6 col-xl-4">
        <div class="card-cutie">
          <img src="<%= cutie.photo %>" />
          <div class="card-cutie-infos">
            <div>
              <h2><%= link_to cutie.name, cuty_path(cutie), class: 'cutie-name' %></h2>
              <p><%= cutie.description %></p>
            </div>
            <div class="card-cutie-user avatar-bordered d-flex justify-content-center align-items-center">
              <p>€<%= '%.2f' % cutie.hourly_price %></p>
            </div>
            <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-cutie-user avatar-bordered" /> -->
          </div>
        </div>
      </div>
      <% end %>
    </div>

  </div>

app/views/cuties/new.html.erb
<div class="container">
  <h1 class= 'text-center my-3'>Add a Cutie to make other people happy</h1>

  <%= simple_form_for [@cutie] do |c| %>
  <%= c.input :ad_title %>
  <%= c.input :name %>
  <%= c.input :animal_type %>
  <%= c.input :age %>
  <%= c.input :gender %>
  <%= c.input :hourly_price %>
  <%= c.input :description %>
  <%= c.input :photo %>
  <%= c.input :photo_cache, as: :hidden %>
  <div style="text-align:center">
  <%= c.submit "Add a cutie", class: 'btn-confirm my-3' %>
  </div>
  <% end %>
</div>

app/views/cuties/show.html.erb
  <div class="container">
    <div class="show-cutie-title-wrapper section">
      <div class="show-cutie-title">
        <h1><%= @cutie.ad_title.capitalize %></h1>
        <h1><strong><%= @cutie.name.capitalize %></strong></h1>
      </div>
    </div>

    <div class="big-cutie-card">

      <div class="show-cutie-body-wrapper">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <div class="show-cutie-body-text">
              <h3>Animal type</h3>
              <p><%= @cutie.animal_type %></p>
              <h3>Age</h3>
              <p><%= @cutie.age%></p>
              <h3>Gender</h3>
              <p><%= @cutie.gender %></p>
              <h3>Hourly price</h3>
              <p>€<%= '%.2f' % @cutie.hourly_price %></p>
              <h3>Description</h3>
              <p><%= @cutie.description %></p>
              <h3>Owner</h3>
              <p><%= @cutie.user.name %></p>
              <% if @cutie.user == current_user %>
              <div>
                <%= link_to "Edit your cutie", edit_cuty_path(@cutie), class: 'btn btn-edit my-1' %>
              </div>
              <div>
                <%= link_to "Remove your cutie", cuty_path(@cutie), method: :delete, class: 'btn btn-remove my-1' %>
              </div>
              <% end %>
            </div>
          </div>


          <div class="col-sm-12 col-md-6">
            <div class="show-cutie-body-and-form">
              <%= cl_image_tag @cutie.photo %>
              <div class="form-wrapper my-1" style="margin: 0;">
                <h2>Rental Agreement</h2>
                <%= simple_form_for [@cutie, rental = Rental.new] do |f| %>
                <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
                <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
                <%= f.button :submit, "Send Rent-Request", class: 'btn btn-confirm'%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <div>
              <%= link_to "Back to Cutie Overview", cuties_path, class: 'btn btn-confirm my-1' %>
            </div>
          </div>
        </div>
      </div>
    </div>



  </div>

app/views/cuties/update.html.erb
<h1>Cuties#update</h1>
<p>Find me in app/views/cuties/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Rent-A-Cutie</title>
  <link rel="icon" type="image/jpg" href="https://res.cloudinary.com/vivelafrans/image/upload/v1566398534/Cuties_logo_eq8qtv.jpg">
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application' %>

  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
<!--   if user is signed in, use the navbar logged in, otherwise logged out -->
  <% if user_signed_in? %>
    <%= render 'shared/navbarli' %>
  <% else %>
    <%= render 'shared/navbarlo' %>
  <% end %>
  <div class="minimum-height">
    <%= yield %>
  </div>
  <div class="footer">
    <div class="footer-copyright">
      This website is made with <i class="fas fa-heart"></i> for animals
    </div>
    <div class="footer-links">
      <a href="https://github.com/Vivelafrans/rent-a-cutie" target="_blank"><i class="fab fa-github"></i></a>
    </div>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/home.html.erb
<!-- <h1>Rent a Cutie!</h1>
<p>The app that allows you to rent cute animals and pick up any girl in the park!</p>
<img src="https://images.unsplash.com/photo-1529778873920-4da4926a72c2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=676&q=80" alt="sweet kitten"> -->

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1559564207-09c99dc78a70?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9);">
  <div class="container">
    <h1>Rent a Cutie!</h1>
    <p>The app that allows you to rent cute animals and brighten your day!</p>
    <!-- <a class="btn btn-secondary" href="#">Come play with us!</a> -->
  </div>
</div>

<div class="container">
  <div class="btn-body">
    <a href="/cuties" class="btn-awesome" data-title="Come play with us!"></a>
  </div>
</div>



<div class="container">
  <div id="carouselControl" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% @cuties.each_with_index do |cutie, i| %>
        <% if i % 3 == 0 %>
        <div class="carousel-item <%= 'active' if cutie == @cuties.first  %>">
        <div class="row">
          <div class="col-xs-12 col-sm-4 col-xl-4">
              <div class="card-cutie">
                <img src="<%= cutie.photo %>" />
                <div class="card-cutie-infos">
                  <div>
                    <h2><%= link_to cutie.name, cuty_path(cutie), class: 'cutie-name' %></h2>
                    <p><%= cutie.description %></p>
                  </div>
                  <h2 class="card-cutie-pricing">€<%= '%.2f' % cutie.hourly_price %></h2>
                </div>

              </div>
          </div>
          <div class="col-xs-12 col-sm-4 col-xl-4">
            <% if @cuties[i + 1] %>
              <% second_cutie = @cuties[i + 1] %>
                <div class="card-cutie">
                  <img src="<%= second_cutie.photo %>" />
                  <div class="card-cutie-infos">
                    <div>
                      <h2><%= link_to second_cutie.name, cuty_path(second_cutie), class: 'cutie-name' %></h2>
                      <p><%= second_cutie.description %></p>
                    </div>
                    <h2 class="card-cutie-pricing">€<%= '%.2f' % second_cutie.hourly_price %></h2>
                  </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-4 col-xl-4">
              <% if @cuties[i + 2] %>
                <% third_cutie = @cuties[i + 2] %>
                  <div class="card-cutie">
                    <img src="<%= third_cutie.photo %>" />
                    <div class="card-cutie-infos">
                      <div>
                        <h2><%= link_to third_cutie.name, cuty_path(third_cutie), class: 'cutie-name' %></h2>
                        <p><%= third_cutie.description %></p>
                      </div>
                      <h2 class="card-cutie-pricing">€<%= '%.2f' % third_cutie.hourly_price %></h2>
                    </div>
                  </div>
              <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>

    <a class="carousel-control-prev carousel-arrows" href="#carouselControl" role="button" data-slide="prev">
      <i class="fas fa-caret-left carret"></i>
    </a>
    <a class="carousel-control-next carousel-arrows" href="#carouselControl" role="button" data-slide="next">
      <i class="fas fa-caret-right carret"></i>
    </a>
    </div>
  </div>
</div>

app/views/rentals/edit.html.erb
<h2>Confirmation of Rental</h2>
<%= simple_form_for [@cutie, @rental] do |f| %>
  <%= f.input :status, collection: ["Confirmed", "Declined"] %>
<%= f.submit "Send", class:"btn-confirm" %>
<% end %>

app/views/rentals/new.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Rental Agreement</h2>

    <%= simple_form_for [@cutie, @rental] do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Send Rent-Request", class: "btn-confirm" %>
    <% end %>
  </div>
  <%= link_to 'Back', cuty_path(@cutie) %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1 class= 'text-center my-3'>Please review the renter:</h1>

  <%= simple_form_for [@cutie, @rental, @review] do |c| %>
  <%= c.input :rating, collection: [ 1, 2, 3, 4, 5 ] %>
  <%= c.input :comment %>
  <div style="text-align:center">
  <%= c.submit "Send the review", class: 'btn btn-confirm' %>
  </div>
  <% end %>
</div>

app/views/shared/_avatar.html.erb
<img class="avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
<img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
<img class="avatar-bordered" alt="avatar-bordered" src="https://kitt.lewagon.com/placeholder/users/sarahlafer" />
<img class="avatar-square" alt="avatar-square" src="https://kitt.lewagon.com/placeholder/users/krokrob" />

app/views/shared/_navbarli.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/vivelafrans/image/upload/v1566398534/Cuties_logo_eq8qtv.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Add Cutie", new_cuty_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "See Cuties", cuties_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "#{current_user.photo}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_navbarlo.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/vivelafrans/image/upload/v1566398534/Cuties_logo_eq8qtv.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Sign-Up", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Sign-In", new_user_session_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="container center">
  <h1 id="header">Dashboard</h1>
  <div class="profile_pic">
    <div class="box-header mt-3">
      <h2>Change your Account data</h2>
    </div>
    <div class="picture"><%= cl_image_tag @user.photo, height: 300, width: 300, crop: :fill %></div>
    <div class="profile_edit mb-3"><%= link_to "Edit your Profile", edit_user_registration_path, class:"btn-edit-2" %></div>
  </div>

  <div class="row" id="db-cards">
    <div class="box-header mt-3">
      <h2 >Your Cuties</h2>
    </div>
    <% @cuties.each do |cutie| %>
    <div class="col-xs-12 col-sm-6 col-xl-4">
      <div class="card-cutie">
        <img src="<%= cutie.photo %>" />
        <div class="card-cutie-infos">
          <div>
            <h2 class="text-left"><%= link_to cutie.name, cuty_path(cutie), class: 'cutie-name' %></h2>
            <p class="text-left"><%= cutie.description %></p>
          </div>
          <div class="card-cutie-user avatar-bordered d-flex justify-content-center align-items-center">
            <p>€<%= '%.2f' % cutie.hourly_price %></p>
          </div>
          <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-cutie-user avatar-bordered" /> -->
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="row" id="db-cards">
    <div class="box-header my-3">
      <h2>Requests for your Cuties</h2>
    </div>
    <% @user.owner_rent_out.each do |r| %>
    <div class="col-xs-12 col-sm-12 col-xl-6">
      <div class = "list_request mx-auto"> <% @cutie = r[0] %> <% @rental = r[1] %> <p class = "pet_name"><%= @cutie.name %></p>
        <div class = "list_item">
          <p><strong>Start-Time:</strong> <%= @rental.start_date %></p>
          <p><strong>End-Time:</strong> <%= @rental.end_date %></p>
          <p><strong>Renter:</strong> <%= @rental.user.name %></p>
          <div class="renter">
          <p class="mr-1" ><strong>Rating:</strong></p>
          <% ratings = [] %>
          <% @rental.user.reviews.each do |ra| %>
            <% ratings << ra.rating.to_i %>
          <% end %>
          <% if ratings.size != 0 %>
            <% rating = ratings.sum / ratings.size unless ratings.size == 0 %>
            <% rating.times do  %>
            <span><i class="fas fa-star"></i></span>
            <% end %>
          <% else %>
          <span>No rating</span>
          <% end %>
          </div>
          <% if @rental.status == "Confirmed" %>
          <p><strong>Rental-Status:</strong>  <span class="green"><%= @rental.status %></span></p>
          <% elsif @rental.status == "Declined" %>
          <p><strong>Rental-Status:</strong>  <span class="red"><%= @rental.status %></span></p>
          <% else %>
          <p><strong>Rental-Status:</strong>  <span><%= @rental.status %></span></p>
          <% end %>
        </div>
        <% if @rental.status == "Pending" %>
        <div id="confirm">
          <%= simple_form_for [@cutie, @rental] do |f| %>
          <%= f.hidden_field :status, value: "Confirmed" %>
          <%= f.submit "Confirm", class:"btn-confirm width", id:"confirm_button"%>
          <% end %>
          <%= simple_form_for [@cutie, @rental] do |f| %>
          <%= f.hidden_field :status, value: "Declined" %>
          <%= f.submit "Decline", class:"btn-confirm width", id:"decline_button"%>
          <% end %>
        </div>
        <% elsif @rental.status == "Confirmed" %>
        <div class="icon_rate">
          <i class="far fa-check-circle"></i>
          <div class="rate-button">
          <%= link_to "Rate", new_cuty_rental_review_path(@cutie, @rental), class: 'btn btn-confirm my-1' %>
          </div>
        </div>
        <% else %>
        <i class="far fa-times-circle"></i>
        <% end %>
      </div>
    </div>
    <% end %>


  </div>

  <div class="row" id="db-cards">
    <div class="box-header my-3">
      <h2>Status of your cutie requests</h2>
    </div>
      <% @user.renter_rent.each do |r| %>
      <div class="col-xs-12 col-sm-12 col-xl-6">
        <div class = "list_request mx-auto">
          <% @cutie = r[0] %> <% @rental = r[1] %>
          <div class="left-side">
            <img src="<%= @cutie.photo %>" class="avatar-large my-auto" />
            <p class = "pet_name_2 my-auto text-center"><%= @cutie.name %></p>
          </div>
          <div class = "list_item">
            <p><strong>Start-Time:</strong> <%= @rental.start_date %></p>
            <p><strong>End-Time:</strong> <%= @rental.end_date %></p>
            <p><strong>Rental-Status:</strong> <%= @rental.status %></p>
          </div>
          <% if @rental.status == "Pending" %>
          <i class="far fa-question-circle"></i>
            <% elsif @rental.status == "Confirmed" %>
          <i class="far fa-check-circle"></i>
          <% else %>
            <i class="far fa-times-circle"></i>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>


  </div>